import { FileCode, Copy, Check } from "lucide-react";
import { useState } from "react";

const netlistCode = `// Two-Stage Folded-Cascode OTA — Iteration #4
// Auto-generated by AIDE v2.4.1


simulator lang=spectre

subckt opamp_v4 (vout vip vin vdd vss)

  // Input differential pair
  M1 (n1 vip n3 vss) nmos w=28u l=0.25u m=4
  M2 (n2 vin n3 vss) nmos w=28u l=0.25u m=4

  // Tail current source
  M3 (n3 vb1 vss vss) nmos w=12u l=0.5u m=2
  I_bias (vdd vb1) isource dc=48u

  // Active load (PMOS)
  M4 (n1 n1 vdd vdd) pmos w=36u l=0.25u m=4
  M5 (n2 n1 vdd vdd) pmos w=36u l=0.25u m=4

  // Second stage
  M6 (vout n2 vdd vdd) pmos w=80u l=0.25u m=8
  M7 (vout vb2 vss vss) nmos w=40u l=0.25u m=4

  // Compensation
  C_c (n2 vout) capacitor c=0.5p
  R_c (n2 nc)   resistor  r=1.2k

ends opamp_v4`;

const NetlistViewer = () => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(netlistCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="panel h-full flex flex-col">
      <div className="panel-header">
        <span className="panel-title flex items-center gap-2">
          <FileCode className="w-3.5 h-3.5 text-info" />
          SPICE Netlist
        </span>
        <button
          onClick={handleCopy}
          className="p-1.5 rounded hover:bg-secondary transition-colors active:scale-95"
        >
          {copied ? (
            <Check className="w-3.5 h-3.5 text-success" />
          ) : (
            <Copy className="w-3.5 h-3.5 text-muted-foreground" />
          )}
        </button>
      </div>
      <div
        className="flex-1 overflow-auto scrollbar-thin p-4"
        style={{ background: "hsl(var(--terminal-bg))" }}
      >
        <pre className="font-mono text-[11px] leading-5 text-secondary-foreground whitespace-pre">
          {netlistCode.split("\n").map((line, i) => (
            <div key={i} className="flex">
              <span className="w-8 text-right mr-4 text-muted-foreground/40 select-none flex-shrink-0">
                {i + 1}
              </span>
              <span
                className={
                  line.trimStart().startsWith("//")
                    ? "text-muted-foreground"
                    : line.includes("subckt") || line.includes("ends")
                    ? "text-primary"
                    : ""
                }
              >
                {line}
              </span>
            </div>
          ))}
        </pre>
      </div>
    </div>
  );
};

export default NetlistViewer;
